# docker-compose.yml

version: '3.8'

services:
  # The FastAPI Backend Application
  backend:
    build: ./backend  # Specifies to build from the Dockerfile in the ./backend directory
    container_name: longevity_api
    ports:
      - "8000:8000" # Exposes the FastAPI port to your local machine
    environment:
      # These variables will be used by your FastAPI app to connect to the database
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your-super-secret-password
    depends_on:
      - neo4j # Ensures that the database is started before the backend starts

  # The Neo4j Database
  neo4j:
    image: neo4j:5.13
    container_name: longevity_db
    ports:
      - "7474:7474" # Web interface (Neo4j Browser)
      - "7687:7687" # Bolt protocol (for the driver)
    environment:
      # Sets the username and password for the database on first run
      - NEO4J_AUTH=neo4j/your-super-secret-password
    volumes:
      - neo4j_data:/data # Persists database data across container restarts

volumes:
  # Defines the named volume for data persistence
  neo4j_data:

